.TH SSH-PUBKEY-FINDER 1 "11 Dec 2025" "0.3.0" "User Commands"
.SH NAME
ssh-pubkey-finder \- find SSH public keys on a system
.SH SYNOPSIS
ssh-pubkey-finder [options]
.SH DESCRIPTION
SSH Pubkey Finder is a Bash script that allows you to retrieve all the authorized SSH public keys on a Linux system.
.SH OPTIONS
.TP
-h
Show help message.
.TP
-u USER
Retrieve the keys only for this user
.TP
-v
Show version.
.SH AUTHOR
Adrien Reymard <adrien.reynard@hevs.ch>
